name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '10.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
  BuildAndPublish:
    needs: BuildAndTest
    runs-on: ubuntu-latest
    name: Update NuGet 
    permissions:
      id-token: write
      packages: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build (Release)
        run: |  
          cd Uni.API
          dotnet build --configuration Release
          dotnet pack --configuration Release

      - name: Publish (Github)
        run: dotnet nuget push "Uni.API/bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/kris701/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

      - name: NuGet login
        uses: NuGet/login@v1
        id: login_nuget
        with:
          user: kris701

      - name: Publish (NuGet)
        run: dotnet nuget push "Uni.API/bin/Release/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ steps.login_nuget.outputs.NUGET_API_KEY }} --skip-duplicate
        
      - name: Get Package version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: Uni.API/Uni.API.csproj

      - name: Generate tag
        continue-on-error: true
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.get-version.outputs.package-version }}"
          message: "Latest release"

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          artifacts: "Uni.API/bin/Release/*.nupkg"
          tag: "v${{ steps.get-version.outputs.package-version }}"

